"""added some new models

Revision ID: 4ac7b8a9c6cf
Revises: 3c1e98208f79
Create Date: 2023-04-16 14:03:47.435269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac7b8a9c6cf'
down_revision = '3c1e98208f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_full', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_table('birdseason',
    sa.Column('birdseason_id', sa.Integer(), nullable=False),
    sa.Column('bird_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bird_id'], ['birds.bird_id'], name=op.f('fk_birdseason_bird_id_birds')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], name=op.f('fk_birdseason_season_id_seasons')),
    sa.PrimaryKeyConstraint('birdseason_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birdseason')
    op.drop_table('seasons')
    # ### end Alembic commands ###
