"""hope this works

Revision ID: c0ec1f5247fd
Revises: 
Create Date: 2023-04-17 20:32:33.493450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ec1f5247fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birds',
    sa.Column('bird_id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('scientific_name', sa.String(), nullable=True),
    sa.Column('body_color', sa.String(), nullable=True),
    sa.Column('beak_color', sa.String(), nullable=True),
    sa.Column('eye_color', sa.String(), nullable=True),
    sa.Column('neck_color', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('swim', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('bird_id')
    )
    op.create_table('locations',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('park_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('seasons',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_full', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('birdseason',
    sa.Column('birdseason_id', sa.Integer(), nullable=False),
    sa.Column('bird_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bird_id'], ['birds.bird_id'], name=op.f('fk_birdseason_bird_id_birds')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], name=op.f('fk_birdseason_season_id_seasons')),
    sa.PrimaryKeyConstraint('birdseason_id')
    )
    op.create_table('sightings',
    sa.Column('sighting_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('bird_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bird_id'], ['birds.bird_id'], name=op.f('fk_sightings_bird_id_birds')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name=op.f('fk_sightings_location_id_locations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_sightings_user_id_users')),
    sa.PrimaryKeyConstraint('sighting_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sightings')
    op.drop_table('birdseason')
    op.drop_table('users')
    op.drop_table('sessions')
    op.drop_table('seasons')
    op.drop_table('locations')
    op.drop_table('birds')
    # ### end Alembic commands ###
